--script do banco

CREATE TABLE ORDER_ENTITY (
    CODE VARCHAR(30) NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    AMOUNT INT NOT NULL,
    DATE DATE NOT NULL,
    VALUE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (CODE)
);